import type { ClothingItem, Category, ColorName, Occasion } from "./types";

/**
 * A starter closet of real garment photography, so the catalog, the filters and
 * the outfit suggestions all do something before the user has photographed
 * anything of their own.
 *
 * Photos are hosted by Unsplash and referenced by URL rather than bundled: the
 * `photoUrl` field is meant to hold a remote object-storage URL in production,
 * so the samples exercise the same path a real item will. Unsplash photos are
 * free to use commercially and require no attribution; every image here was
 * reviewed individually before being added. Item names describe what is in the
 * photograph — they are not a claim about who made or owns the garment.
 *
 * Wear history is spread out on purpose: it's what makes "longest unworn"
 * sorting and the rotation-aware ranker visibly do something on first run.
 */

type SampleSpec = {
  /** Stable across releases — the top-up seeder matches on it. */
  id: string;
  name: string;
  category: Category;
  color: ColorName;
  /** Unsplash photo id — used for the generic wardrobe staples. */
  photo?: string;
  /** StockX product slug — used for specific sneakers, which Unsplash lacks. */
  sneaker?: string;
  /**
   * Demo filler (cleared by "Clear examples") vs. something the owner asked to
   * catalogue, which behaves like anything they added themselves.
   */
  sample?: boolean;
  occasions: Occasion[];
  tags: string[];
  /** Days since last worn; `null` means never worn. */
  wornDaysAgo: number | null;
  wearCount: number;
};

const SAMPLES: SampleSpec[] = [
  {
    id: "sample-1",
    name: "Air Jordan 1",
    category: "shoes",
    color: "red",
    photo: "photo-1552346154-21d32810aba3",
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["leather", "high-top"],
    wornDaysAgo: 3,
    wearCount: 24,
  },
  {
    id: "sample-2",
    name: "Black Leather Boots",
    category: "shoes",
    color: "black",
    photo: "photo-1534233812932-59b8fa1b780c",
    occasions: ["work", "interview", "formal", "date-night"],
    tags: ["leather", "resoled 2025"],
    wornDaysAgo: 34,
    wearCount: 9,
  },
  {
    id: "sample-3",
    name: "White Running Trainers",
    category: "shoes",
    color: "white",
    photo: "photo-1600185365926-3a2ce3cdb9eb",
    occasions: ["everyday", "active", "weekend"],
    tags: ["mesh", "gym"],
    wornDaysAgo: 9,
    wearCount: 16,
  },
  {
    id: "sample-4",
    name: "Black Leather Sneakers",
    category: "shoes",
    color: "black",
    photo: "photo-1543508282-6319a3e2621f",
    occasions: ["everyday", "work", "date-night"],
    tags: ["leather"],
    wornDaysAgo: 52,
    wearCount: 5,
  },
  {
    id: "sample-5",
    name: "White Dress Shirt",
    category: "shirt",
    color: "white",
    photo: "photo-1602810316498-ab67cf68c8e1",
    occasions: ["work", "interview", "formal", "date-night"],
    tags: ["cotton", "iron before wearing"],
    wornDaysAgo: 21,
    wearCount: 12,
  },
  {
    id: "sample-6",
    name: "White Crewneck Tee",
    category: "shirt",
    color: "white",
    photo: "photo-1651761179569-4ba2aa054997",
    occasions: ["everyday", "weekend", "active"],
    tags: ["cotton"],
    wornDaysAgo: 2,
    wearCount: 31,
  },
  {
    id: "sample-7",
    name: "Black Graphic Tee",
    category: "shirt",
    color: "black",
    photo: "photo-1583743814966-8936f5b7be1a",
    occasions: ["everyday", "weekend"],
    tags: ["cotton", "print"],
    wornDaysAgo: 47,
    wearCount: 6,
  },
  {
    id: "sample-8",
    name: "White Sweatshirt",
    category: "shirt",
    color: "white",
    photo: "photo-1620799140408-edc6dcb6d633",
    occasions: ["everyday", "weekend", "active"],
    tags: ["fleece-backed"],
    wornDaysAgo: 14,
    wearCount: 19,
  },
  {
    id: "sample-9",
    name: "Light Wash Jeans",
    category: "pants",
    color: "blue",
    photo: "photo-1602293589930-45aad59ba3ab",
    occasions: ["everyday", "weekend"],
    tags: ["denim"],
    wornDaysAgo: 4,
    wearCount: 42,
  },
  {
    id: "sample-10",
    name: "Black Jeans",
    category: "pants",
    color: "black",
    photo: "photo-1718252540617-6ecda2b56b57",
    occasions: ["everyday", "work", "interview", "date-night"],
    tags: ["denim", "slim"],
    wornDaysAgo: 62,
    wearCount: 7,
  },
  {
    id: "sample-11",
    name: "Dark Indigo Jeans",
    category: "pants",
    color: "navy",
    photo: "photo-1624378439575-d8705ad7ae80",
    occasions: ["everyday", "work", "weekend"],
    tags: ["denim", "raw"],
    wornDaysAgo: 16,
    wearCount: 11,
  },
  {
    id: "sample-12",
    name: "Rust Trousers",
    category: "pants",
    color: "red",
    photo: "photo-1590159983013-d4ff5fc71c1d",
    occasions: ["weekend", "everyday"],
    tags: ["wide leg"],
    wornDaysAgo: 88,
    wearCount: 3,
  },
  {
    id: "sample-13",
    name: "Black Suit Jacket",
    category: "jacket",
    color: "black",
    photo: "photo-1592343516109-362f7bd871aa",
    occasions: ["interview", "work", "formal", "date-night"],
    tags: ["wool", "dry clean"],
    wornDaysAgo: 96,
    wearCount: 4,
  },
  {
    id: "sample-14",
    name: "Denim Jacket",
    category: "jacket",
    color: "blue",
    photo: "photo-1611312449408-fcece27cdbb7",
    occasions: ["everyday", "weekend"],
    tags: ["denim", "spring"],
    wornDaysAgo: 12,
    wearCount: 8,
  },
  {
    id: "sample-15",
    name: "Black Leather Jacket",
    category: "jacket",
    color: "black",
    photo: "photo-1551028719-00167b16eac5",
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["leather"],
    wornDaysAgo: 41,
    wearCount: 10,
  },
  {
    id: "sample-16",
    name: "Brown Leather Belt",
    category: "accessory",
    color: "brown",
    photo: "photo-1624222247344-550fb60583dc",
    occasions: ["everyday", "work", "interview", "formal"],
    tags: ["leather"],
    wornDaysAgo: 21,
    wearCount: 18,
  },
  {
    id: "sample-17",
    name: "Two-Tone Watch",
    category: "accessory",
    color: "grey",
    photo: "photo-1639006570490-79c0c53f1080",
    occasions: ["everyday", "work", "interview", "date-night"],
    tags: ["steel", "needs new battery"],
    wornDaysAgo: 1,
    wearCount: 54,
  },
];

/**
 * Items the owner asked to catalogue. Not demo filler: these survive "Clear
 * examples" and behave exactly like anything captured in-app.
 *
 * Sneaker photography comes from StockX's product CDN, because Unsplash, Pexels
 * and Wikimedia have no Foamposite imagery at all and naming a picture of a
 * different shoe "Foamposite" would be a lie the catalog then repeats forever.
 * Every image below was opened and checked against its colourway before being
 * added. These are a retailer's copyrighted product shots — fine for a personal
 * catalog, worth replacing with your own photos before this is ever public.
 */
const OWNED: SampleSpec[] = [
  {
    id: "foam-eggplant",
    name: 'Air Foamposite One "Eggplant"',
    category: "shoes",
    color: "purple",
    sneaker: "Nike-Air-Foamposite-One-Eggplant-2024",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["foamposite", "2024"],
    wornDaysAgo: 11,
    wearCount: 14,
  },
  {
    id: "foam-galaxy",
    name: 'Air Foamposite One "Galaxy"',
    category: "shoes",
    color: "multi",
    sneaker: "Nike-Air-Foamposite-One-Galaxy-2025",
    sample: false,
    occasions: ["weekend"],
    tags: ["foamposite", "2025", "deadstock"],
    wornDaysAgo: null,
    wearCount: 0,
  },
  {
    id: "foam-copper",
    name: 'Air Foamposite One "Copper"',
    category: "shoes",
    color: "brown",
    sneaker: "Nike-Air-Foamposite-One-Copper-2024",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["foamposite", "2024"],
    wornDaysAgo: 73,
    wearCount: 4,
  },
  {
    id: "foam-cough-drop",
    name: 'Air Foamposite One "Cough Drop"',
    category: "shoes",
    color: "red",
    sneaker: "Nike-Air-Foamposite-One-Cough-Drop-2025",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["foamposite", "2025"],
    wornDaysAgo: 29,
    wearCount: 6,
  },
  {
    id: "foam-triple-white",
    name: 'Air Foamposite One "Triple White"',
    category: "shoes",
    color: "white",
    sneaker: "Nike-Air-Foamposite-One-Triple-White",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["foamposite", "keep clean"],
    wornDaysAgo: 140,
    wearCount: 2,
  },
  {
    id: "foam-black-volt",
    name: 'Air Foamposite One "Black Volt"',
    category: "shoes",
    color: "green",
    sneaker: "Nike-Air-Foamposite-One-Black-Volt",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["foamposite", "2025"],
    wornDaysAgo: 8,
    wearCount: 12,
  },
  {
    id: "foam-tekken",
    name: 'Air Foamposite One "Tekken 8"',
    category: "shoes",
    color: "grey",
    sneaker: "Nike-Air-Foamposite-One-Tekken-8-Jin-Kazama",
    sample: false,
    occasions: ["weekend"],
    tags: ["foamposite", "collab"],
    wornDaysAgo: null,
    wearCount: 0,
  },
  {
    id: "aj4-bred",
    name: 'Jordan 4 Retro "Bred Reimagined"',
    category: "shoes",
    color: "black",
    sneaker: "Air-Jordan-4-Retro-Bred-Reimagined",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["jordan", "retro"],
    wornDaysAgo: 6,
    wearCount: 21,
  },
  {
    id: "aj4-white-cement",
    name: 'Jordan 4 Retro "White Cement"',
    category: "shoes",
    color: "white",
    sneaker: "Air-Jordan-4-Retro-White-Cement-2025",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["jordan", "retro"],
    wornDaysAgo: 19,
    wearCount: 9,
  },
  {
    id: "aj3-white-cement",
    name: 'Jordan 3 Retro "White Cement Reimagined"',
    category: "shoes",
    color: "white",
    sneaker: "Air-Jordan-3-Retro-White-Cement-Reimagined",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["jordan", "retro"],
    wornDaysAgo: 44,
    wearCount: 7,
  },
  {
    id: "aj11-concord-bred",
    name: 'Jordan 11 Retro Low "Concord Bred"',
    category: "shoes",
    color: "white",
    sneaker: "Air-Jordan-11-Retro-Low-Concord-Bred",
    sample: false,
    occasions: ["everyday", "date-night", "weekend"],
    tags: ["jordan", "patent leather"],
    wornDaysAgo: 33,
    wearCount: 5,
  },
  {
    id: "aj11-bred-low",
    name: 'Jordan 11 Retro Low "Bred"',
    category: "shoes",
    color: "black",
    sneaker: "Air-Jordan-11-Retro-Low-Bred-2025",
    sample: false,
    occasions: ["everyday", "date-night", "work"],
    tags: ["jordan", "patent leather"],
    wornDaysAgo: 2,
    wearCount: 17,
  },
  {
    id: "aj1-85-bred",
    name: "Jordan 1 Retro High '85 \"Bred\"",
    category: "shoes",
    color: "red",
    sneaker: "Air-Jordan-1-Retro-High-85-Bred",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["jordan", "og"],
    wornDaysAgo: 57,
    wearCount: 3,
  },
  // Streetwear lane: Yeezy-era silhouettes and boxy earth-tone layers.
  {
    id: "yz-zebra",
    name: 'Yeezy Boost 350 V2 "Zebra"',
    category: "shoes",
    color: "white",
    sneaker: "adidas-Yeezy-Boost-350-V2-Zebra",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["yeezy", "primeknit"],
    wornDaysAgo: 7,
    wearCount: 22,
  },
  {
    id: "yz-onyx",
    name: 'Yeezy Boost 350 V2 "Onyx"',
    category: "shoes",
    color: "black",
    sneaker: "adidas-Yeezy-Boost-350-V2-Onyx",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["yeezy", "primeknit"],
    wornDaysAgo: 3,
    wearCount: 19,
  },
  {
    id: "yz-cream",
    name: 'Yeezy Boost 350 V2 "Cream White"',
    category: "shoes",
    color: "white",
    sneaker: "adidas-Yeezy-Boost-350-V2-Cream-White",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["yeezy", "keep clean"],
    wornDaysAgo: 31,
    wearCount: 8,
  },
  {
    id: "yz-beluga",
    name: 'Yeezy Boost 350 V2 "Beluga Reflective"',
    category: "shoes",
    color: "grey",
    sneaker: "adidas-Yeezy-Boost-350-V2-Beluga-Reflective",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["yeezy", "reflective"],
    wornDaysAgo: 58,
    wearCount: 6,
  },
  {
    id: "yz-alien",
    name: 'Yeezy Boost 380 "Alien"',
    category: "shoes",
    color: "grey",
    sneaker: "adidas-Yeezy-Boost-380-Alien",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["yeezy", "glow sole"],
    wornDaysAgo: 20,
    wearCount: 9,
  },
  {
    id: "yz-slide",
    name: 'Yeezy Slide "Pure"',
    category: "shoes",
    color: "tan",
    sneaker: "adidas-Yeezy-Slide-Pure",
    sample: false,
    occasions: ["everyday"],
    tags: ["yeezy", "slide", "house shoe"],
    wornDaysAgo: 1,
    wearCount: 61,
  },
  {
    id: "dunk-panda",
    name: 'Nike Dunk Low "Panda"',
    category: "shoes",
    color: "white",
    sneaker: "Nike-Dunk-Low-Retro-White-Black-2021",
    sample: false,
    occasions: ["everyday", "weekend", "work"],
    tags: ["dunk", "leather"],
    wornDaysAgo: 5,
    wearCount: 34,
  },
  {
    id: "aj3-black-cement",
    name: 'Jordan 3 Retro "Black Cement"',
    category: "shoes",
    color: "black",
    sneaker: "Air-Jordan-3-Retro-Black-Cement-2018",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["jordan", "elephant print"],
    wornDaysAgo: 26,
    wearCount: 13,
  },
  {
    id: "own-hoodie-sand",
    name: "Sand Oversized Hoodie",
    category: "shirt",
    color: "tan",
    photo: "photo-1564557287817-3785e38ec1f5",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["hoodie", "oversized", "earth tone"],
    wornDaysAgo: 2,
    wearCount: 29,
  },
  {
    id: "own-hoodie-bone",
    name: "Bone Oversized Hoodie",
    category: "shirt",
    color: "white",
    photo: "photo-1688111421205-a0a85415b224",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["hoodie", "oversized", "earth tone"],
    wornDaysAgo: 12,
    wearCount: 17,
  },
  {
    id: "own-hoodie-charcoal",
    name: "Charcoal Hoodie",
    category: "shirt",
    color: "grey",
    photo: "photo-1677538537484-324385aff147",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["hoodie"],
    wornDaysAgo: 18,
    wearCount: 14,
  },
  {
    id: "own-cargo-khaki",
    name: "Khaki Cargo Pants",
    category: "pants",
    color: "tan",
    photo: "photo-1511794322962-129ddbd0af38",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["cargo", "utility", "earth tone"],
    wornDaysAgo: 10,
    wearCount: 20,
  },
  {
    id: "own-parachute-black",
    name: "Black Parachute Pants",
    category: "pants",
    color: "black",
    photo: "photo-1783012687000-26e994270984",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["baggy", "technical"],
    wornDaysAgo: 8,
    wearCount: 23,
  },
  {
    id: "own-stonewash-jeans",
    name: "Stonewash Jeans",
    category: "pants",
    color: "blue",
    photo: "photo-1784639072018-dd85c44f992e",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["denim", "light wash"],
    wornDaysAgo: 9,
    wearCount: 15,
  },
  {
    id: "own-faded-jeans",
    name: "Faded Blue Jeans",
    category: "pants",
    color: "blue",
    photo: "photo-1777572551291-fb0f9a39ceeb",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["denim", "light wash"],
    wornDaysAgo: 23,
    wearCount: 10,
  },
  {
    id: "own-varsity-brown",
    name: "Brown Varsity Jacket",
    category: "jacket",
    color: "brown",
    photo: "photo-1771310961705-c8b34eddbe9e",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["varsity", "wool"],
    wornDaysAgo: 15,
    wearCount: 9,
  },
  {
    id: "own-varsity-red",
    name: "Red Varsity Jacket",
    category: "jacket",
    color: "red",
    photo: "photo-1760458955495-9712cc8f79c0",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["varsity", "letterman"],
    wornDaysAgo: 38,
    wearCount: 5,
  },
  {
    id: "own-bomber-red",
    name: "Red Bomber Jacket",
    category: "jacket",
    color: "red",
    photo: "photo-1782132047241-a4c6d7ae792c",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["bomber"],
    wornDaysAgo: 51,
    wearCount: 3,
  },
  {
    id: "timb-big",
    name: 'Timberland 6" Premium "Notorious B.I.G."',
    category: "shoes",
    color: "tan",
    sneaker: "Timberland-6-Premium-Boot-The-Notorious-BIG-Wheat",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["timberland", "wheat", "nubuck"],
    wornDaysAgo: 13,
    wearCount: 11,
  },
  {
    id: "timb-avirex",
    name: 'Timberland 6" Premium "Avirex"',
    category: "shoes",
    color: "tan",
    sneaker: "Timberland-6-Premium-Waterproof-Boot-Avirex-Wheat",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["timberland", "wheat", "waterproof"],
    wornDaysAgo: 66,
    wearCount: 4,
  },
  {
    id: "own-yankees-cap",
    name: "New York Yankees Cap",
    category: "accessory",
    color: "navy",
    photo: "photo-1747257490779-5bdae916478f",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["fitted", "new york"],
    wornDaysAgo: 1,
    wearCount: 48,
  },
  // The two below have no photo on purpose. There is no freely-licensed
  // photography of a Louis Vuitton scarf or a New York team jacket anywhere I
  // could verify — Unsplash, Pexels, Wikimedia and StockX's product CDN all
  // came up empty — and dressing up a stand-in would put a wrong picture in the
  // catalog permanently. They're logged with their tags so suggestions can use
  // them; tap the tile to shoot the real thing.
  {
    id: "own-lv-scarf",
    name: "Louis Vuitton Monogram Scarf",
    category: "accessory",
    color: "brown",
    sample: false,
    occasions: ["everyday", "date-night", "work"],
    tags: ["scarf", "monogram", "winter"],
    wornDaysAgo: 26,
    wearCount: 7,
  },
  {
    id: "own-ny-jacket",
    name: "New York Yankees Jacket",
    category: "jacket",
    color: "navy",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["new york", "satin", "bomber"],
    wornDaysAgo: 4,
    wearCount: 16,
  },
  {
    id: "own-black-tee",
    name: "Black T-Shirt",
    category: "shirt",
    color: "black",
    photo: "photo-1618354691373-d851c5c3a990",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["cotton"],
    wornDaysAgo: 5,
    wearCount: 27,
  },
  {
    id: "own-blue-jeans",
    name: "Blue Jeans",
    category: "pants",
    color: "blue",
    photo: "photo-1624378441864-6eda7eac51cb",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["denim"],
    wornDaysAgo: 6,
    wearCount: 33,
  },
  // Wale lane: the DMV sneaker canon, his own merch, DC sports and the
  // designer/streetwear mix he's photographed in. Only the four sneakers below
  // have real photography — StockX has product shots for those. The apparel is
  // brand-specific (tour merch, a team jersey, a patched jacket) and no
  // freely-licensed photograph of the actual garment exists, so it's catalogued
  // photo-less rather than illustrated with a stand-in that shows the wrong
  // thing. Tap a tile to shoot the real one.
  {
    id: "wale-foamposite-dmv",
    name: 'Air Foamposite One "DMV"',
    category: "shoes",
    color: "pink",
    sneaker: "Nike-Air-Foamposite-One-DMV-Cherry-Blossom",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["foamposite", "dmv", "cherry blossom", "2024"],
    wornDaysAgo: 5,
    wearCount: 12,
  },
  {
    id: "wale-goadome",
    name: "Nike Air Max Goadome",
    category: "shoes",
    color: "black",
    sneaker: "Nike-Air-Max-Goadome-Black",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["acg", "nike boots", "winter", "leather"],
    wornDaysAgo: 16,
    wearCount: 20,
  },
  {
    id: "wale-af1-white",
    name: "Nike Air Force 1 '07",
    category: "shoes",
    color: "white",
    sneaker: "Nike-Air-Force-1-07-White",
    sample: false,
    occasions: ["everyday", "weekend", "work"],
    tags: ["af1", "leather", "keep clean"],
    wornDaysAgo: 2,
    wearCount: 40,
  },
  {
    id: "wale-yeezy2-red-october",
    name: 'Nike Air Yeezy 2 "Red October"',
    category: "shoes",
    color: "red",
    sneaker: "Nike-Air-Yeezy-2-Red-October",
    sample: false,
    occasions: ["weekend", "date-night"],
    tags: ["grail", "deadstock"],
    wornDaysAgo: null,
    wearCount: 0,
  },
  {
    id: "wale-bottle-rocket",
    name: 'ASICS Gel-Lyte III "Bottle Rocket"',
    category: "shoes",
    color: "black",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["asics", "villa collab", "suede", "3m"],
    wornDaysAgo: 62,
    wearCount: 5,
  },
  {
    id: "wale-ebm-tee",
    name: "Every Blue Moon Tour Tee",
    category: "shirt",
    color: "black",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["merch", "graphic", "cotton"],
    wornDaysAgo: 4,
    wearCount: 18,
  },
  {
    id: "wale-chocolate-city-crew",
    name: "Chocolate City Cherry Blossom Crewneck",
    category: "shirt",
    color: "pink",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["merch", "dc", "crewneck"],
    wornDaysAgo: 12,
    wearCount: 9,
  },
  {
    id: "wale-wizards-jersey",
    name: "Washington Wizards Jersey",
    category: "shirt",
    color: "red",
    sample: false,
    occasions: ["weekend", "active"],
    tags: ["nba", "dc", "mesh"],
    wornDaysAgo: 9,
    wearCount: 14,
  },
  {
    id: "wale-bape-shark-hoodie",
    name: "BAPE Shark Full-Zip Hoodie",
    category: "shirt",
    color: "multi",
    sample: false,
    occasions: ["everyday", "weekend"],
    tags: ["bape", "camo", "hoodie"],
    wornDaysAgo: 21,
    wearCount: 7,
  },
  {
    id: "wale-ysl-black-jeans",
    name: "Saint Laurent Slim Black Jeans",
    category: "pants",
    color: "black",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["denim", "slim", "designer"],
    wornDaysAgo: 7,
    wearCount: 22,
  },
  {
    id: "wale-dmv-patch-jacket",
    name: "DMV Flag Patch Leather Jacket",
    category: "jacket",
    color: "black",
    sample: false,
    occasions: ["everyday", "weekend", "date-night"],
    tags: ["leather", "dmv", "patches"],
    wornDaysAgo: 30,
    wearCount: 6,
  },
  {
    id: "wale-nats-cap",
    name: "Washington Nationals Fitted Cap",
    category: "accessory",
    color: "navy",
    sample: false,
    occasions: ["everyday", "weekend", "active"],
    tags: ["fitted", "dc", "curly w"],
    wornDaysAgo: 3,
    wearCount: 26,
  },
];

/** Bump when entries are added, so existing installs top up once. */
export const SEED_VERSION = 5;

const DAY_MS = 24 * 60 * 60 * 1000;

/** Square, cropped, quality-capped — the shape the catalog grid expects. */
function unsplashUrl(id: string): string {
  return `https://images.unsplash.com/${id}?w=900&h=900&fit=crop&crop=entropy&q=75&auto=format`;
}

/** StockX product shots are already centred on white; just size them. */
function stockxUrl(slug: string): string {
  return `https://images.stockx.com/images/${slug}-Product.jpg?w=900&q=80`;
}

function resolvePhoto(spec: SampleSpec): string | null {
  if (spec.sneaker) return stockxUrl(spec.sneaker);
  if (spec.photo) return unsplashUrl(spec.photo);
  return null;
}

/** Builds the sample closet. Called once, on a first run with an empty store. */
export function buildSampleCloset(now = Date.now()): ClothingItem[] {
  return [...SAMPLES, ...OWNED].map((spec, index) => ({
    id: spec.id,
    // Staggered so "Newest" ordering is stable and doesn't look machine-made.
    createdAt: new Date(now - index * 37 * 60 * 1000).toISOString(),
    photoUrl: resolvePhoto(spec),
    name: spec.name,
    category: spec.category,
    color: spec.color,
    tags: spec.tags,
    occasions: spec.occasions,
    lastWornAt:
      spec.wornDaysAgo === null ? null : new Date(now - spec.wornDaysAgo * DAY_MS).toISOString(),
    wearCount: spec.wearCount,
    isSample: spec.sample ?? true,
  }));
}
